name: Pandoc Document Converter

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - run: |
            sed -e 's/<!--//g' readme.md > tmp.md
            sed -i -e 's/-->//g' tmp.md

      - name: Pandoc Build
        uses: maxheld83/pandoc-action@v2
        with:
          args: tmp.md --standalone --css=assets/main.css --metadata pagetitle="Bookmarklets" --output=public/index.html
      
      - run: rm -f tmp.md

      - name: Add & Commit
        uses: EndBug/add-and-commit@v4.1.0
        with:
          message: 'update site content from sources'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
